<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Dymatrix.Notifications.Application\Dymatrix.Notifications.Application.csproj" />
    <ProjectReference Include="..\Dymatrix.Notifications.Infrastructure\Dymatrix.Notifications.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d353d8f1-fb93-415c-a49e-d5b0074caf74</UserSecretsId>
  </PropertyGroup>

</Project>
